sudo: required
services:
  - docker
language: ruby
rvm:
- 2.3.1
notifications:
  email: false
  slack:
    secure: gXeWbGGhKBielZsaDPfu1YWagffUTxE6ZSa1ypEhGhSEIBPZt+IFwyjMF37B7C2gVfkZv+BkorffxoqbYJRQ3JkXKj21Ns+aJYNvS9FDG3OGQeWm9thHNZDXOKJRTkMWGF62DlGjaxp4Rm3aGAFF63uQWKSKn0vTQEXcJ1CBVrk2BPzUtPQKuL04EkuBscvTmRoT/9Lv69f/bV7VsWkYN3LzFqOwuVYe7BtvByIQQz77js9f3vnUWB3tgYzWu5/lj6aJs8/aZMet3CgBro/271sL/vKGdAUmjRwYIeLY1qd6w+JR7Cj9EsmPDvRCtw6Yyww/NT+mUtnu3GYK54CGylpx3fQ3lNmBgDXDepFH809nrj08CX4XRjhEKRm7AoOifXkoIU2HZP0SQH/BkPza3Plevw+XNCMtCuehqdCYzejCs7dkoJ7qfDc2y46Qm4lBe8Z5NRJJ4LJHZNXMbQCrvCEYCC1HzemsiJ81O6hnsUvfMksL9GOCT+CZGzyuW5T8wI8u0Hufx3mkR0jYAI/pXVi1aJSFCFL5I/mC8SPbfExQiQ5sEENR4KltDODQOOS5wd37zq26Q2KEaIkc7IBJEc39f4OqVCVRDmkvqYjbHDBBRz7C2FPoFb2Ym/NOPd3ai+ruvo+7csR44iMKNlrH2wva/7M58Q7yeIIdMTmCgp4=
branches:
  only:
  - master
  - integration
before_install:
  - sudo apt-get install xmlsec1 libxmlsec1-dev
  - docker build -t hydea .
  #- docker run hydea /bin/sh -c "cd /usr/src/app; bundle exec rspec"
before_script: bundle exec rake db:migrate RAILS_ENV=test
after_success:
  - if [ "$TRAVIS_BRANCH" == "integration" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com;
    docker tag hydea registry.heroku.com/hydea-qa/web;
    docker push registry.heroku.com/hydea-qa/web;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com;
    docker tag hydea registry.heroku.com/hydea/web;
    docker push registry.heroku.com/hydea/web;
    fi
